import Foundation

enum HuntObjectCringeLines {
  private static let linesByObjectID: [String: [String]] = [
    "coffee_mug": [
      "Found the coffee mug. Still searching for your future.",
      "Coffee can wake you up. It can't fix your life.",
      "That's a nice mug. Shame about the owner.",
      "Even the mug has a purpose this morning.",
      "Found coffee. Now find some ambition.",
      "Your coffee works harder than you do.",
      "The mug is full. Your schedule isn't.",
      "Holding that mug like it's your emotional support animal.",
      "The mug gets more attention than your gym membership.",
      "Careful. You're looking at that mug the way successful people look at opportunities.",
      "At least someone's hot this morning.",
    ],
    "water_bottle": [
      "Water bottle found. Shower next, hopefully.",
      "Good. You're hydrated. Still useless, but hydrated.",
      "Your bottle has been carrying you for years.",
      "Water detected. Character development not detected.",
      "Drink water. Your excuses are dehydrated.",
      "Even this bottle leaves the house more than you.",
      "The bottle is the only thing getting filled consistently around here.",
      "You finally grabbed something healthy. Character development.",
      "That's a nice bottle. Compensation for something?",
      "Looking thirsty this early is wild.",
    ],
    "toothbrush": [
      "Toothbrush found. Society thanks you.",
      "Good morning. Your breath was a war crime.",
      "The toothbrush is doing all the heavy lifting.",
      "Found the toothbrush. Friends saved.",
      "Your dentist just felt a disturbance in the force.",
      "At least something in your life gets cleaned regularly.",
    ],
    "pillow": [
      "Pillow found. The toxic relationship continues.",
      "Bro went straight to the pillow. We knew it.",
      "The pillow misses you more than your ex.",
      "Nice try. The pillow isn't your soulmate.",
      "Put the pillow down and chase your dreams. They're already running away.",
      "The pillow has seen more commitment than your goals.",
      "You really know how to handle a pillow. Shame about your goals.",
      "Back on the pillow already? Buy it dinner first.",
      "The way you keep coming back to that pillow... suspicious.",
      "You and that pillow need some time apart.",
    ],
    "clock": [
      "Clock found. Time to disappoint people in real time.",
      "The clock is moving forward. Try it sometime.",
      "Congratulations. You're late emotionally.",
      "The clock can't carry your life forever.",
      "Time is money. You're overdrafting.",
      "The clock has watched you waste years.",
    ],
    "laptop": [
      "Laptop found. Those unread emails are getting stronger.",
      "Your laptop just remembered your responsibilities.",
      "Work called. It hung up.",
      "The laptop is awake. The effort isn't.",
      "Found the laptop. Success not included.",
      "Your screen time is impressive. Your results aren't.",
      "Looking at the laptop won't make the work disappear.",
      "Open the laptop. The problems are inside.",
      "The laptop has seen searches it can never forget.",
      "Your laptop knows too much.",
    ],
    "book": [
      "Found a book. That's the closest you've been to knowledge all week.",
      "The book has more chapters than your life plan.",
      "Reading won't fix this but it's a start.",
      "The book believes in you. Rookie mistake.",
      "Knowledge located. Application missing.",
      "The book is trying harder than you are.",
    ],
    "chair": [
      "Chair found. Sit down and achieve nothing.",
      "That's the throne of procrastination.",
      "The chair has witnessed every delayed dream.",
      "Don't sit. We both know how this ends.",
      "That chair owes you rent.",
      "Your chair sees you more than sunlight does.",
      "The chair knows exactly what you're about to do. Nothing.",
      "Sit on that chair and your productivity dies instantly.",
      "The chair has supported you more than your last situationship.",
      "That's not a chair. That's a trap.",
    ],
    "banana": [
      "Found the banana. The internet has ruined this fruit.",
      "Holding a banana at 6 AM is a risky move.",
      "We found the banana. Let's keep this family-friendly.",
      "Interesting object choice. Very interesting.",
      "Interesting choice of object. Very interesting.",
      "The banana has more potassium than your personality.",
      "Holding that banana confidently is wild.",
      "The banana is healthier than your routine.",
    ],
    "hair_dryer": [
      "Hair dryer found. Shame it can't dry your tears.",
      "The hair dryer has a hotter future than you.",
      "Found the dryer. Confidence not included.",
      "Your hair is fixable. Your sleep schedule isn't.",
      "The dryer is working overtime. Like your excuses.",
      "Looking fresh won't fool your responsibilities.",
    ],
    "microwave": [
      "Microwave found. MasterChef dreams not found.",
      "The microwave has achieved more in 30 seconds than you all week.",
      "Found the microwave. Dinner still won't cook itself.",
      "Your leftovers have a better comeback story than you.",
      "Beep. Another meal closer to greatness. You're not.",
      "The microwave is carrying this household.",
    ],
    "refrigerator": [
      "Fridge found. Your goals aren't in there.",
      "Checked the fridge again? Nothing changed.",
      "The fridge knows your secrets.",
      "Found the fridge. Self-control missing.",
      "You're opening the fridge like it owes you answers.",
      "The fridge has seen more consistency than your habits.",
    ],
    "television": [
      "TV found. Productivity found dead nearby.",
      "The TV misses you. Your goals don't.",
      "Netflix is asking if you're still wasting time.",
      "Found the TV. Character development postponed.",
      "The TV has custody of your attention span.",
      "One more episode away from ruining tomorrow.",
      "One more episode and suddenly it's tomorrow.",
    ],
    "keyboard": [
      "Keyboard found. Time to type excuses professionally.",
      "The keyboard is ready. Your work ethic isn't.",
      "Found the keyboard. Promotion not included.",
      "Your keyboard gets touched more than your goals.",
      "The keyboard remembers every bad decision.",
      "Type faster. Success is still waiting.",
    ],
    "mouse": [
      "Mouse found. Still easier to catch than opportunities.",
      "Your mouse moves more than you do.",
      "Found the mouse. Ambition still loading.",
      "Clicking random things counts as cardio now?",
      "The mouse is doing all the traveling.",
      "You move the cursor. Not your life.",
    ],
    "orange": [
      "Orange found. Vitamin C carrying your entire team.",
      "The orange is working harder than your immune system.",
      "Found the orange. Motivation still unavailable.",
      "The orange has more layers than your life plan.",
      "Fresh fruit. Same old problems.",
      "The orange showed up today. Match the effort.",
    ],
  ]

  static func randomLine(for objectID: String) -> String? {
    linesByObjectID[objectID]?.randomElement()
  }

  static func randomLine(for object: HuntObject) -> String? {
    randomLine(for: object.id)
  }
}
